-- Choco Planner: authentification, roles et versions de planning.
-- Executer ce fichier une seule fois dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'viewer'
    check (role in ('admin', 'planner', 'production', 'viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.planning_versions (
  id uuid primary key default gen_random_uuid(),
  factory_id text not null,
  name text not null,
  period_start date not null,
  period_end date not null,
  version_no integer not null default 1,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'replaced', 'archived')),
  snapshot jsonb not null,
  created_by uuid not null references auth.users(id),
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  unique(factory_id, period_start, period_end, version_no)
);

create table if not exists public.planning_actuals (
  id uuid primary key default gen_random_uuid(),
  planning_version_id uuid not null references public.planning_versions(id) on delete cascade,
  slot_key text not null,
  actual_kg numeric,
  note text not null default '',
  updated_by uuid not null references auth.users(id),
  updated_at timestamptz not null default now(),
  unique(planning_version_id, slot_key)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  planning_version_id uuid references public.planning_versions(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.production_priorities (
  id uuid primary key default gen_random_uuid(),
  factory_id text not null,
  rule_type text not null
    check (rule_type in ('never_stockout', 'sequence', 'due_date', 'boosted_target')),
  product_id text not null,
  after_product_id text,
  priority integer not null default 50 check (priority between 1 and 100),
  target_multiplier numeric not null default 1.5 check (target_multiplier between 1 and 4),
  due_date date,
  note text not null default '',
  active boolean not null default true,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.production_line_settings (
  factory_id text not null,
  line_id text not null,
  active boolean not null default true,
  updated_by uuid not null references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (factory_id, line_id)
);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role from public.profiles where id = auth.uid() and active = true),
    'viewer'
  );
$$;

create or replace function public.admin_list_users()
returns table (
  id uuid,
  email text,
  full_name text,
  role text,
  active boolean,
  created_at timestamptz,
  last_sign_in_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    u.id,
    u.email::text,
    p.full_name,
    p.role,
    p.active,
    u.created_at,
    u.last_sign_in_at
  from auth.users u
  join public.profiles p on p.id = u.id
  where public.current_app_role() = 'admin'
  order by lower(u.email);
$$;

revoke all on function public.admin_list_users() from public;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.manage_planning_version(
  p_version_id uuid,
  p_action text,
  p_name text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_version public.planning_versions%rowtype;
  v_role text;
begin
  select * into v_version from public.planning_versions where id = p_version_id;
  if not found then
    raise exception 'Version no encontrada.';
  end if;

  v_role := public.current_app_role();
  if v_role <> 'admin'
     and not (v_role = 'planner' and v_version.status = 'draft' and v_version.created_by = auth.uid()) then
    raise exception 'No tienes permiso para gestionar esta version.';
  end if;

  if p_action = 'rename' then
    if nullif(trim(p_name), '') is null then
      raise exception 'El nombre no puede estar vacio.';
    end if;
    update public.planning_versions set name = trim(p_name) where id = p_version_id;
  elsif p_action = 'archive' then
    if v_role <> 'admin' then raise exception 'Solo un admin puede archivar.'; end if;
    update public.planning_versions set status = 'archived' where id = p_version_id;
  elsif p_action = 'restore' then
    if v_role <> 'admin' then raise exception 'Solo un admin puede restaurar.'; end if;
    update public.planning_versions set status = 'approved' where id = p_version_id;
  elsif p_action = 'delete' then
    if v_role <> 'admin' then raise exception 'Solo un admin puede eliminar una version.'; end if;
    delete from public.planning_versions where id = p_version_id;
  else
    raise exception 'Accion no valida.';
  end if;

  insert into public.audit_events (user_id, planning_version_id, action, details)
  values (
    auth.uid(),
    case when p_action = 'delete' then null else p_version_id end,
    'planning_version_' || p_action,
    jsonb_build_object('version_id', p_version_id, 'name', v_version.name, 'status', v_version.status)
  );
end;
$$;

revoke all on function public.manage_planning_version(uuid, text, text) from public;
grant execute on function public.manage_planning_version(uuid, text, text) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.protect_approved_planning()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('approved', 'replaced', 'archived')
     and (new.snapshot is distinct from old.snapshot
       or new.factory_id is distinct from old.factory_id
       or new.period_start is distinct from old.period_start
       or new.period_end is distinct from old.period_end
       or new.version_no is distinct from old.version_no) then
    raise exception 'Una planificacion aprobada no puede modificarse. Crea una revision.';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists protect_approved_planning_trigger on public.planning_versions;
create trigger protect_approved_planning_trigger
  before update on public.planning_versions
  for each row execute procedure public.protect_approved_planning();

alter table public.profiles enable row level security;
alter table public.planning_versions enable row level security;
alter table public.planning_actuals enable row level security;
alter table public.audit_events enable row level security;
alter table public.production_priorities enable row level security;
alter table public.production_line_settings enable row level security;

drop policy if exists "Authenticated users read profiles" on public.profiles;
create policy "Authenticated users read profiles"
  on public.profiles for select to authenticated using (true);

drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles"
  on public.profiles for update to authenticated
  using (public.current_app_role() = 'admin')
  with check (public.current_app_role() = 'admin');

drop policy if exists "Authenticated users read planning versions" on public.planning_versions;
create policy "Authenticated users read planning versions"
  on public.planning_versions for select to authenticated using (true);

drop policy if exists "Planners create planning versions" on public.planning_versions;
create policy "Planners create planning versions"
  on public.planning_versions for insert to authenticated
  with check (
    public.current_app_role() in ('admin', 'planner')
    and created_by = auth.uid()
  );

drop policy if exists "Planners update drafts" on public.planning_versions;
create policy "Planners update drafts"
  on public.planning_versions for update to authenticated
  using (
    public.current_app_role() in ('admin', 'planner')
    and status = 'draft'
  )
  with check (public.current_app_role() in ('admin', 'planner'));

drop policy if exists "Authenticated users read actuals" on public.planning_actuals;
create policy "Authenticated users read actuals"
  on public.planning_actuals for select to authenticated using (true);

drop policy if exists "Production writes actuals" on public.planning_actuals;
create policy "Production writes actuals"
  on public.planning_actuals for insert to authenticated
  with check (
    public.current_app_role() in ('admin', 'planner', 'production')
    and updated_by = auth.uid()
  );

drop policy if exists "Production updates actuals" on public.planning_actuals;
create policy "Production updates actuals"
  on public.planning_actuals for update to authenticated
  using (public.current_app_role() in ('admin', 'planner', 'production'))
  with check (
    public.current_app_role() in ('admin', 'planner', 'production')
    and updated_by = auth.uid()
  );

drop policy if exists "Authenticated users read audit" on public.audit_events;
create policy "Authenticated users read audit"
  on public.audit_events for select to authenticated using (true);

drop policy if exists "Authenticated users create audit" on public.audit_events;
create policy "Authenticated users create audit"
  on public.audit_events for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Authenticated users read production priorities" on public.production_priorities;
create policy "Authenticated users read production priorities"
  on public.production_priorities for select to authenticated using (true);

drop policy if exists "Admins create production priorities" on public.production_priorities;
drop policy if exists "Editors create production priorities" on public.production_priorities;
create policy "Editors create production priorities"
  on public.production_priorities for insert to authenticated
  with check (public.current_app_role() in ('admin', 'planner', 'production') and created_by = auth.uid());

drop policy if exists "Admins update production priorities" on public.production_priorities;
drop policy if exists "Editors update production priorities" on public.production_priorities;
create policy "Editors update production priorities"
  on public.production_priorities for update to authenticated
  using (public.current_app_role() in ('admin', 'planner', 'production'))
  with check (public.current_app_role() in ('admin', 'planner', 'production'));

drop policy if exists "Admins delete production priorities" on public.production_priorities;
drop policy if exists "Editors delete production priorities" on public.production_priorities;
create policy "Editors delete production priorities"
  on public.production_priorities for delete to authenticated
  using (public.current_app_role() in ('admin', 'planner', 'production'));

drop policy if exists "Authenticated users read production line settings" on public.production_line_settings;
create policy "Authenticated users read production line settings"
  on public.production_line_settings for select to authenticated using (true);

drop policy if exists "Planners create production line settings" on public.production_line_settings;
create policy "Planners create production line settings"
  on public.production_line_settings for insert to authenticated
  with check (public.current_app_role() in ('admin', 'planner') and updated_by = auth.uid());

drop policy if exists "Planners update production line settings" on public.production_line_settings;
create policy "Planners update production line settings"
  on public.production_line_settings for update to authenticated
  using (public.current_app_role() in ('admin', 'planner'))
  with check (public.current_app_role() in ('admin', 'planner') and updated_by = auth.uid());

create index if not exists planning_versions_factory_period_idx
  on public.planning_versions(factory_id, period_start desc, period_end desc);
create index if not exists planning_actuals_version_idx
  on public.planning_actuals(planning_version_id);
create index if not exists production_priorities_factory_idx
  on public.production_priorities(factory_id, active, priority desc);
create index if not exists production_line_settings_factory_idx
  on public.production_line_settings(factory_id, active, line_id);
