-- Choco Planner: authentification, roles et versions de planning.
-- Executer ce fichier une seule fois dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'viewer'
    check (role in ('admin', 'planner', 'production', 'viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.planning_versions (
  id uuid primary key default gen_random_uuid(),
  factory_id text not null,
  name text not null,
  period_start date not null,
  period_end date not null,
  version_no integer not null default 1,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'replaced', 'archived')),
  snapshot jsonb not null,
  created_by uuid not null references auth.users(id),
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  unique(factory_id, period_start, period_end, version_no)
);

create table if not exists public.planning_actuals (
  id uuid primary key default gen_random_uuid(),
  planning_version_id uuid not null references public.planning_versions(id) on delete cascade,
  slot_key text not null,
  actual_kg numeric,
  note text not null default '',
  updated_by uuid not null references auth.users(id),
  updated_at timestamptz not null default now(),
  unique(planning_version_id, slot_key)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  planning_version_id uuid references public.planning_versions(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role from public.profiles where id = auth.uid() and active = true),
    'viewer'
  );
$$;

create or replace function public.admin_list_users()
returns table (
  id uuid,
  email text,
  full_name text,
  role text,
  active boolean,
  created_at timestamptz,
  last_sign_in_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    u.id,
    u.email::text,
    p.full_name,
    p.role,
    p.active,
    u.created_at,
    u.last_sign_in_at
  from auth.users u
  join public.profiles p on p.id = u.id
  where public.current_app_role() = 'admin'
  order by lower(u.email);
$$;

revoke all on function public.admin_list_users() from public;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.protect_approved_planning()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('approved', 'replaced', 'archived')
     and (new.snapshot is distinct from old.snapshot
       or new.factory_id is distinct from old.factory_id
       or new.period_start is distinct from old.period_start
       or new.period_end is distinct from old.period_end
       or new.version_no is distinct from old.version_no) then
    raise exception 'Una planificacion aprobada no puede modificarse. Crea una revision.';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists protect_approved_planning_trigger on public.planning_versions;
create trigger protect_approved_planning_trigger
  before update on public.planning_versions
  for each row execute procedure public.protect_approved_planning();

alter table public.profiles enable row level security;
alter table public.planning_versions enable row level security;
alter table public.planning_actuals enable row level security;
alter table public.audit_events enable row level security;

drop policy if exists "Authenticated users read profiles" on public.profiles;
create policy "Authenticated users read profiles"
  on public.profiles for select to authenticated using (true);

drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles"
  on public.profiles for update to authenticated
  using (public.current_app_role() = 'admin')
  with check (public.current_app_role() = 'admin');

drop policy if exists "Authenticated users read planning versions" on public.planning_versions;
create policy "Authenticated users read planning versions"
  on public.planning_versions for select to authenticated using (true);

drop policy if exists "Planners create planning versions" on public.planning_versions;
create policy "Planners create planning versions"
  on public.planning_versions for insert to authenticated
  with check (
    public.current_app_role() in ('admin', 'planner')
    and created_by = auth.uid()
  );

drop policy if exists "Planners update drafts" on public.planning_versions;
create policy "Planners update drafts"
  on public.planning_versions for update to authenticated
  using (
    public.current_app_role() in ('admin', 'planner')
    and status = 'draft'
  )
  with check (public.current_app_role() in ('admin', 'planner'));

drop policy if exists "Authenticated users read actuals" on public.planning_actuals;
create policy "Authenticated users read actuals"
  on public.planning_actuals for select to authenticated using (true);

drop policy if exists "Production writes actuals" on public.planning_actuals;
create policy "Production writes actuals"
  on public.planning_actuals for insert to authenticated
  with check (
    public.current_app_role() in ('admin', 'planner', 'production')
    and updated_by = auth.uid()
  );

drop policy if exists "Production updates actuals" on public.planning_actuals;
create policy "Production updates actuals"
  on public.planning_actuals for update to authenticated
  using (public.current_app_role() in ('admin', 'planner', 'production'))
  with check (
    public.current_app_role() in ('admin', 'planner', 'production')
    and updated_by = auth.uid()
  );

drop policy if exists "Authenticated users read audit" on public.audit_events;
create policy "Authenticated users read audit"
  on public.audit_events for select to authenticated using (true);

drop policy if exists "Authenticated users create audit" on public.audit_events;
create policy "Authenticated users create audit"
  on public.audit_events for insert to authenticated
  with check (user_id = auth.uid());

create index if not exists planning_versions_factory_period_idx
  on public.planning_versions(factory_id, period_start desc, period_end desc);
create index if not exists planning_actuals_version_idx
  on public.planning_actuals(planning_version_id);
